name: UniversalStaffWatch
version: @version@-@apiversion@
author: DartPower
website: https://github.com/dptmc/UniversalStaffWatch
main: io.dpteam.UniversalStaffWatch.Main
commands:
  watch:
    description: Watch a player
    usage: |
      Usage:
      /<command> [player] - Watch a player
  unwatch:
    description: Stop watching a player
    usage: |
      Usage:
      /<command> - Stop watching a player
